server:
  port: 8761

spring:
  application:
    name: discovery-service

# eureka 라이브러리가 포함되어 있으면 무조건 eureka.client 로 등록을 시도함.
# eureka.client.register-with-eureka, eureka.client.fetch-registry 설정 값의 기본 값이 true 이므로
# Eureka 서버 등록 시에는 false로 명시적으로 설정 해 주어야 함.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
